[package]
distribution = "2201.8.6"
org = "ballerinax"
name = "zendesk"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["zendesk", "CRM", "CSM", "Support/Customer Support", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-zendesk"

[build-options]
observabilityIncluded = false

[platform.java17]
graalvmCompatible = true
